(library
 (name compiler)
 (libraries core)
 (preprocess (pps ppx_jane ppx_deriving.show))
 (modules
   Apex
   Count
   Elaborate
   Elaboration
   Lexeme
   LexemeData
   Lexer
   Lexical
   Lift
   Pratt
   PrettyPrinter
   Procedural
   ProceduralBackend
   Symbol
   SymbolData
   Syntax
   SyntaxData
   ThreeAddress
   Translate
   Types
   )
 )

(rule
 (target Lexer.ml)
 (deps   Lexer.mll)
 (action (chdir %{workspace_root}
          (run %{bin:ocamllex} -q -o %{target} %{deps}))))

(env
 (dev
  (flags
   (:standard -warn-error -A)
)))
